namespace CompanyLookupApi.Dtos;

public sealed record CompanyResponse(
    string Cif,
    string CompanyName,
    string? TradingName,
    string? Segment,
    string? LegalEntityName,
    string? Country,
    string? RegistrationNumber,
    string? LegalForm,
    DateTime? DateOfIncorporation,
    string? TaxIdVat,
    string? Address,
    int? NumberOfEmployees,
    string? Industry,
    string? OwnerName,
    decimal? OwnershipPercentage,
    string? NationalId,
    string? BoardOfDirectors,
    string? SignatoryAuthority,
    decimal? AnnualTurnover,
    decimal? WorkingCapital,
    decimal? YtdTurnover,
    decimal? NetProfit,
    decimal? TotalAssets,
    decimal? TotalLiabilities,
    decimal? ShareholdersEquity);